apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        readinessProbe: #tells Kubernetes “I’m ready to accept connections”
          tcpSocket:
            port: 5672       # rabbitmq port
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe: #tells Kubernetes “restart me if I’m unhealthy”
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10

---
apiVersion: v1 #service api vesion is "v1"while "deployments is apps/v1"
kind: Service
metadata:
  name: rabbitmq #servicename = DNS name for the rabbitmq deployement
  namespace: roboshop #Selector + namespace must match
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 65672

