apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: ramanadockerhub/mongodb:v1
        readinessProbe: #tells Kubernetes “I’m ready to accept connections”
          tcpSocket:
            port: 27017        # MongoDB port
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe: #tells Kubernetes “restart me if I’m unhealthy”
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb #servicename = DNS name for the mongodb deployement
#   namespace: roboshop #Selector + namespace must match
# spec:
#   selector:
#     project: roboshop
#     component: mongodb
#     tier: db
#   ports:
#   - protocol: TCP
#     port: 27017
#     targetPort: 27017

