apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: ramanadockerhub/mongodb:v1
        readinessProbe:
          tcpSocket:
            port: 27017        # MongoDB port
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop #namespace must be same as deployment
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

