apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop #namespsceshould be rohoshop else it will be degfault 
  # these are replica set labels
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop #check thhis indentation
      component: mongodb
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: ramanadockerhub/mongodb:v1
        readinessPorbe:
          tcpSockets:
            port: 27107
        intialDelaySeconds: 10
        periodSeconds: 10  
        livenessPorbe: #health chcek
          tcpSockets: 
          port: 27017
        intialDelaySeconds: 5
        periodSeconds: 5


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
# spec:
#   selector:
#     project: roboshop
#     component: mongodb
#     tier: db
#   ports:
#   - protocol: TCP
#     port: 27017        # Service port
#     targetPort: 27017 # Pod container port
   
