apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: ramanadockerhub/mysql:v1
        imagePullPolicy: Always
        readinessProbe: #tells Kubernetes “I’m ready to accept connections”
          tcpSocket:
            port: 3306        # mysql port
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe: #tells Kubernetes “restart me if I’m unhealthy”
          tcpSocket:
            port: 3306
          initialDelaySeconds: 90
          periodSeconds: 5

---
apiVersion: v1 #service api vesion is "v1"while "deployments is apps/v1"
kind: Service
metadata:
  name: mysql #servicename = DNS name for the mysql deployement
  namespace: roboshop #Selector + namespace must match
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

