apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop 
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image: ramanadockerhub/user:v1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: user
        ports: #just for information
        - name: liveness-port
          containerPort: 8080
        readinessProbe: #tells Kubernetes “I’m ready to accept connections”
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15  
        livenessProbe: #tells Kubernetes “restart me if I’m unhealthy”
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: v1 #service api vesion is "v1"while "deployments is apps/v1"
kind: Service
metadata:
  name: user #servicename = DNS name for the mongodb deployement
  namespace: roboshop #Selector + namespace must match
spec:
  selector:
    project: roboshop
    component: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

